name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    env:
        USER_NAME: ${{ secrets.USER_NAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        URL: "https://balme.ug.edu.gh/past.exampapers/index.php?p=member"
        TOKEN: ${{ secrets.TOKEN }}
        DEVELOPER_CHAT_ID: ${{ secrets.DEVELOPER_CHAT_ID}}
        PORT: "5000"
    
    steps:
        - name: Checkout Code
          uses: actions/checkout@v2
        
        - name: Set Up Python 3.10
          uses: actions/setup-python@v2
          with:
            python-version: "3.10"
          
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r requirements-dev.txt  
          continue-on-error: true
    
        - name: Check Installation Status
          run: |
            if [ $? -ne 0 ]; then
                echo "Dependency installation failed!"
                exit 1
            fi

        - name: Unit and Integration Tests
          run: |
            python -m unit -v 
            python -m integration -v
